### ISSUE TITLE
Media Playback Asynchronicity

### ISSUE THREAD

**Issue by DJStompZone** [GenieTim/OneDriveStreamer#2]
When an audio file is played, if the user then exits the player activity and attempts to play/enqueue another song, it is played simultaneously without stopping the currently playing audio. Furthermore, there's no readily visible way to return to the original song in order to stop/pause it, other than force closing the app.
How feasible would it be to implement background audio functionality through the system UI, or at least a persistent view to allow for the user to return to the currently active player?
Cool project btw, the OneDrive auth worked flawlessly

**Comment by GenieTim** [comment]
Thanks for your feedback. I admit, I only ever used the app myself for videos, I guess that's where this oversight has come from. I will see what I can do somewhen the week after next, and will come back to this issue once I did.

**Comment by GenieTim** [comment]
In [dc2ab57](https://github.com/GenieTim/OneDriveStreamer/commit/dc2ab5780fd12a6203ea07b4f09431feeb88f296), I have implemented as a fix that I would stop the media before leaving the player page. I admit, this is far from the best solution, but due to time constraints, I do not think it makes sense for me to try implementing some sort of a small YouTube-like "now playing" frame.

Feel free to open a PR if you have time to implement a better solution, I would be happy to review, merge and publish.

The corresponding package has been submitted to the store.
